version: '2'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: Testify
      MYSQL_USER: Testifyuser
      MYSQL_PASSWORD: bananas
  web:
    image: iliapa1/testify:1.0
    env_file: env_web
    command: ./wait_for_db.sh
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
