version: '2'

services:

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 12345646
      MYSQL_DATABASE: Testify
      MYSQL_USER: Testifyuser
      MYSQL_PASSWORD: bananas
    volumes:
      - ./dbdata:/var/lib/mysql

  web:
    # Docker hack to wait until Postgres is up, then run stuff.
    command: bash -c "while ! nc -w 1 -z db 3306; do sleep 0.1; done; ./manage.py migrate; while :; do ./manage.py runserver_plus 0.0.0.0:8000; sleep 1; done"
    image: testify:1.0
    build: .
    volumes:
      - .:/code
    links:
      - db
    environment:
      IN_DOCKER: 1

  webserver:
    image: jumanjiman/caddy
    depends_on:
      - web
    ports:
      - "80:8000"
    command: -port 8000 -host 0.0.0.0 "proxy / web:8000 { }"
