---
 

- name: Install build-essential
  apt: name=build-essential state=present update_cache=yes

- name: Create a started container
  lxd_container:
    name: "{{ item }}"
    state: started
    source:
      type: image
      mode: pull
      protocol: lxd
      alias: Base1
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
# make one more 
  with_items:
     - mycontainer0
     - mycontainer1
     - mycontainer2
     - mycontainer3
  register: containers_info

- name: Wait for the network to be setup in the containers
  when: containers_info|changed
  pause: seconds=10

- name: Register the hosts in the inventory
  add_host:
    name: "{{ containers_info.results[item].addresses.eth0[0] }}"
    ansible_ssh_private_key_file: /root/ssh/id_rsa_ansible
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null"
    groups: containers 
  with_items:
    - 0
    - 1
    - 2
    - 3

