---
- name: Create a started container
  lxd_container:
    name: "{{ item }}"
    state: started
    source:
      type: image
      mode: pull
      protocol: lxd
      alias: Base
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
# make one more 
  with_items:
     - mycontainer1
     - mycontainer2
  register: containers_info

# because missing repository from git in first
- name: Delete a contain
  lxd_container:
    name: mycontainer1
    state: absent

- name: Wait for the network to be setup in the containers
  when: containers_info|changed
  pause: seconds=5

- name: Register the hosts in the inventory
  add_host:
    name: "{{ containers_info.results[0-1].addresses.eth0[0] }}"
    ansible_ssh_private_key_file: /home/ilia/.ssh/id_rsa_ansible 
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null"
