---
 

- name: Install build-essential
  apt: name=build-essential state=present update_cache=yes

- name: Create a started container for app
  lxd_container:
    name: Testify
    state: started
    source:
      type: image
      mode: pull
      protocol: lxd
      alias: Image
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
    config: 
      type: physical
      name: eth0
      subnets:
        type: static
        ipv4: true
        address: ["10.10.10.10"]
        control: auto
  register: containers_info_app
  
- name: Create a started container for db
  lxd_container:
    name: "{{ item }}"
    state: started
    source:
      type: image
      mode: pull
      protocol: lxd
      alias: Image
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
# make one more 
  with_items:
     - Mariadb
  register: containers_info_db


- name: Wait for the network to be setup in the containers
  when: containers_info_app|changed
  pause: seconds=10

- name: Wait for the network to be setup in the containers
  when: containers_info_db|changed
  pause: seconds=10


- name: Register the hosts in the group app
  add_host: 
    name: "{{ containers_info_app.results[item].addresses.eth0[0] }}"
    ansible_ssh_private_key_file: /root/ssh/id_rsa_ansible
    ansible_ssh_common_argsjust_created: "-o UserKnownHostsFile=/dev/null"
    groups: app_containers
  with_items:
    - 0
    - 1


- name: Register the hosts in the group db
  add_host: 
    name: "{{ containers_info_db.results[item].addresses.eth0[0] }}"
    ansible_ssh_private_key_file: /root/ssh/id_rsa_ansible
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null"
    groups: db_containers
  with_items:
    - 0
