---
- hosts: localhost
  connection: local
  become: true
  roles:
    - iliapa.image-download
    - iliapa.ssh
    - iliapa.lxd


- hosts: app_containers
  become: true
  gather_facts: False
  roles:
     - iliapa.python2_app
     - iliapa.pkgs_app
     - role: iliapa.clone-rep_app
       git_repository: https://github.com/iliapa1/Testify.git
     - iliapa.pip-requirements_app 
     - iliapa.service-restart_app

- hosts: db_containers
  become: true
  gather_facts: False
  roles:
     - iliapa.python2_db
     - iliapa.pkgs_db
     - role: iliapa.clone-rep_db
       git_repository: https://github.com/iliapa1/Testify.git
     - iliapa.pip-requirements_db
     - role: iliapa.mariadb_db
       database_name: Testify
       database_user: db_user
       database_password: bananas
     - iliapa.service-restart_db

- hosts: localhost
  connection: local
  become: true
  roles:
    - iliapa.service-restart_local



    

  




 



