---
- hosts: localhost
  connection: local
  become: true
  roles:
    - iliapa.image-download
    - iliapa.lxd


- hosts: all
  become: true
  gather_facts: False
  roles:
    - iliapa.python2
    - iliapa.pkgs
    - iliapa.clone-rep
    - iliapa.pip-requirements
    - iliapa.mariadb


  




 



