---

- name: set haproxy
  template:
    src: templates/haproxy.cfg 
    dest: /etc/haproxy/
    owner: root
    group: root  

- name: restart haproxy
  systemd:
    state: restarted
    daemon_reload: yes
    name: haproxy
