---
# tasks file for ansible-role-heroku-cli
- name: Add Heroku toolbelt repo
  apt_repository:
    repo: deb https://cli-assets.heroku.com/branches/stable/apt ./

- name: Add the Heroku apt key
  apt_key:
    url: https://cli-assets.heroku.com/apt/release.key
    state: present

- name: Update APT package cache
  apt: update_cache=yes

- name: Install heroku
  apt: name={{ item }} state=installed update_cache=yes allow_unauthenticated=yes
  become: true
  with_items:
    - heroku
